# Golden Age Project by Dwayne Pringle


##### A basic python project

## Introduction <a id='intro'></a>
In this project, you will work with data from the entertainment industry. You will study a dataset with records on movies and shows. The research will focus on the "Golden Age" of television, which began in 1999 with the release of *The Sopranos* and is still ongoing.

The aim of this project is to investigate how the number of votes a title receives impacts its ratings. The assumption is that highly-rated shows (we will focus on TV shows, ignoring movies) released during the "Golden Age" of television also have the most votes.

## Stage 1. Data overview <a id='data_review'></a>

Open and explore the data.

In [ ]:
# importing pandas
import pandas as pd

In [ ]:
# reading the files and storing them to df
df = pd.read_csv('/datasets/movies_and_shows.csv')

Print the first 10 table rows:

In [ ]:
# obtaining the first 10 rows from the df table
# hint: you can use head() and tail() in Jupyter Notebook without wrapping them into print()
first_ten_rows = df[0:10]
print(first_ten_rows)

              name                      Character   r0le        TITLE   Type  \
0   Robert De Niro                  Travis Bickle  ACTOR  Taxi Driver  MOVIE
1     Jodie Foster                  Iris Steensma  ACTOR  Taxi Driver  MOVIE
2    Albert Brooks                            Tom  ACTOR  Taxi Driver  MOVIE
3    Harvey Keitel        Matthew 'Sport' Higgins  ACTOR  Taxi Driver  MOVIE
4  Cybill Shepherd                          Betsy  ACTOR  Taxi Driver  MOVIE
5      Peter Boyle                         Wizard  ACTOR  Taxi Driver  MOVIE
6   Leonard Harris      Senator Charles Palantine  ACTOR  Taxi Driver  MOVIE
7   Diahnne Abbott                Concession Girl  ACTOR  Taxi Driver  MOVIE
8      Gino Ardito             Policeman at Rally  ACTOR  Taxi Driver  MOVIE
9  Martin Scorsese  Passenger Watching Silhouette  ACTOR  Taxi Driver  MOVIE

   release Year              genres  imdb sc0re  imdb v0tes
0          1976  ['drama', 'crime']         8.2    808582.0
1          1976  ['drama', 'crime']         8.2    808582.0
2          1976  ['drama', 'crime']         8.2    808582.0
3          1976  ['drama', 'crime']         8.2    808582.0
4          1976  ['drama', 'crime']         8.2    808582.0
5          1976  ['drama', 'crime']         8.2    808582.0
6          1976  ['drama', 'crime']         8.2    808582.0
7          1976  ['drama', 'crime']         8.2    808582.0
8          1976  ['drama', 'crime']         8.2    808582.0
9          1976  ['drama', 'crime']         8.2    808582.0

In [ ]:
# obtaining general information about the data in df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85579 entries, 0 to 85578
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0      name       85579 non-null  object
 1   Character     85579 non-null  object
 2   r0le          85579 non-null  object
 3   TITLE         85578 non-null  object
 4     Type        85579 non-null  object
 5   release Year  85579 non-null  int64
 6   genres        85579 non-null  object
 7   imdb sc0re    80970 non-null  float64
 8   imdb v0tes    80853 non-null  float64
dtypes: float64(2), int64(1), object(6)
memory usage: 5.9+ MB

### Conclusions <a id='data_review_conclusions'></a> 

Each row in the table stores data about a movie or show. The columns can be divided into two categories: the first is about the roles held by different people who worked on the movie or show (role, name of the actor or director, and character if the row is about an actor); the second category is information about the movie or show itself (title, release year, genre, imdb figures).

It's clear that there is sufficient data to do the analysis and evaluate our assumption. However, to move forward, we need to preprocess the data.

## Stage 2. Data preprocessing <a id='data_preprocessing'></a>
Correcting the formatting in the column headers and deal with the missing values. Then, checking whether there are duplicates in the data.

In [ ]:
# the list of column names in the df table
print(df.columns)

Index(['   name', 'Character', 'r0le', 'TITLE', '  Type', 'release Year',
       'genres', 'imdb sc0re', 'imdb v0tes'],
      dtype='object')

Change the column names according to the rules of good style:
* If the name has several words, use snake_case
* All characters must be lowercase
* Remove whitespace
* Replace zero with letter 'o'

In [ ]:
# renaming columns
df = df.rename(columns = {'   name':'name',
                          'Character':'character',
                          'r0le':'role',
                          'TITLE': 'title',
                          '  Type': 'type',
                          'release Year': 'release_year',
                          'imdb sc0re': 'imdb_score',
                          'imdb v0tes': 'imdb_votes'})

Check the result. Print the names of the columns once more:

In [ ]:
# checking result: the list of column names
print(df.columns)

Index(['name', 'character', 'role', 'title', 'type', 'release_year', 'genres',
       'imdb_score', 'imdb_votes'],
      dtype='object')

### Missing values <a id='missing_values'></a>
First, find the number of missing values in the table. To do so, combine two `pandas` methods:

In [ ]:
# calculating missing values
print(df.isna().sum())

name               0
character          0
role               0
title              1
type               0
release_year       0
genres             0
imdb_score      4609
imdb_votes      4726
dtype: int64

We identified missing values in several columns. While the missing value in `'title'` isn't critical, missing values in `'imdb_score'` and `'imdb_votes'` affect around 6% of the data, which could impact our analysis. To ensure data integrity, we'll drop all rows with missing values.

In [ ]:
# dropping rows where columns with scores, and votes have missing values
df = df.dropna(axis = 'rows')

Make sure the table doesn't contain any more missing values. Count the missing values again.

In [ ]:
# counting missing values
print(df.isna().sum())

name            0
character       0
role            0
title           0
type            0
release_year    0
genres          0
imdb_score      0
imdb_votes      0
dtype: int64

### Duplicates <a id='duplicates'></a>
Find the number of duplicate rows in the table using one command:

In [ ]:
# counting duplicate rows
print(df.duplicated().sum())

6994

Review the duplicate rows to determine if removing them would distort our dataset.

In [ ]:
# Produce table with duplicates (with original rows included) and review last 5 rows
last_5_rows = df[:]
print(last_5_rows)

                     name                character      role        title  \
0          Robert De Niro            Travis Bickle     ACTOR  Taxi Driver
1            Jodie Foster            Iris Steensma     ACTOR  Taxi Driver
2           Albert Brooks                      Tom     ACTOR  Taxi Driver
3           Harvey Keitel  Matthew 'Sport' Higgins     ACTOR  Taxi Driver
4         Cybill Shepherd                    Betsy     ACTOR  Taxi Driver
...                   ...                      ...       ...          ...
85574    Adelaida Buscato               Mar??a Paz     ACTOR      Lokillo
85575  Luz Stella Luengas             Karen Bayona     ACTOR      Lokillo
85576        In??s Prieto                    Fanny     ACTOR      Lokillo
85577        Isabel Gaona                   Cacica     ACTOR      Lokillo
85578      Julian Gaviria                  unknown  DIRECTOR      Lokillo

            type  release_year              genres  imdb_score  imdb_votes
0          MOVIE          1976  ['drama', 'crime']         8.2    808582.0
1          MOVIE          1976  ['drama', 'crime']         8.2    808582.0
2          MOVIE          1976  ['drama', 'crime']         8.2    808582.0
3          MOVIE          1976  ['drama', 'crime']         8.2    808582.0
4          MOVIE          1976  ['drama', 'crime']         8.2    808582.0
...          ...           ...                 ...         ...         ...
85574  the movie          2021          ['comedy']         3.8        68.0
85575  the movie          2021          ['comedy']         3.8        68.0
85576  the movie          2021          ['comedy']         3.8        68.0
85577      MOVIE          2021          ['comedy']         3.8        68.0
85578  the movie          2021          ['comedy']         3.8        68.0

[80853 rows x 9 columns]

There are two clear duplicates in the printed rows. We can safely remove them.
Call the `pandas` method for getting rid of duplicate rows:

In [ ]:
# removing duplicate rows
df = df.drop_duplicates()
df.reset_index(drop=True)

,name,character,role,title,type,release_year,genres,imdb_score,imdb_votes
0,Robert De Niro,Travis Bickle,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
1,Jodie Foster,Iris Steensma,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
2,Albert Brooks,Tom,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
3,Harvey Keitel,Matthew 'Sport' Higgins,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
4,Cybill Shepherd,Betsy,ACTOR,Taxi Driver,MOVIE,1976,"['drama', 'crime']",8.2,808582.0
...,...,...,...,...,...,...,...,...,...
73854,A??da Morales,Maritza,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
73855,Adelaida Buscato,Mar??a Paz,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
73856,Luz Stella Luengas,Karen Bayona,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
73857,In??s Prieto,Fanny,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
73858,Julian Gaviria,unknown,DIRECTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0

Check for duplicate rows once more to make sure you have removed all of them:

In [ ]:
# checking for duplicates
df.duplicated().sum()

0

Now get rid of implicit duplicates in the `'type'` column. For example, the string `'SHOW'` can be written in different ways. These kinds of errors will also affect the result.

Print a list of unique `'type'` names, sorted in alphabetical order. To do so:
* Retrieve the intended dataframe column 
* Apply a sorting method to it
* For the sorted column, call the method that will return all unique column values

In [ ]:
# viewing unique type names
unique_types = df['type'].str.lower().unique()
sorted_types = df.sort_values(by= 'type', ascending = False)
print(sorted_types)

                   name                                          character  \
2207     Unsho Ishizuka                                  Jet Black (voice)
1274      David Carling  Station Officer Steele / Chief Fire Officer Bo...
1276      Tegwen Tucker        Penny / Sarah / Bronwyn / Mrs. Chen (voice)
1277    Harriet Kershaw                              Ellie / Bella (voice)
1278          Alex Lowe                                  Ben / Joe (voice)
...                 ...                                                ...
26649  Iliza Shlesinger                                            Herself
26650       Ryan Polito                                            unknown
26651    Kangana Ranaut                                        Payal Ahuja
26652        Imran Khan                               Madhav 'Maddy' Kabra
37793       Tyrone Neal                         Wedding Guest (uncredited)

           role                           title      type  release_year  \
2207      ACTOR                    Cowboy Bebop  tv shows          1998
1274      ACTOR                     Fireman Sam  tv shows          1987
1276      ACTOR                     Fireman Sam  tv shows          1987
1277      ACTOR                     Fireman Sam  tv shows          1987
1278      ACTOR                     Fireman Sam  tv shows          1987
...         ...                             ...       ...           ...
26649     ACTOR  Iliza Shlesinger: Freezing Hot     MOVIE          2015
26650  DIRECTOR  Iliza Shlesinger: Freezing Hot     MOVIE          2015
26651     ACTOR                     Katti Batti     MOVIE          2015
26652     ACTOR                     Katti Batti     MOVIE          2015
37793     ACTOR                           Naked     MOVIE          2017

                                                  genres  imdb_score  \
2207   ['animation', 'action', 'scifi', 'western', 'c...         8.9
1274   ['animation', 'comedy', 'family', 'crime', 'eu...         6.1
1276   ['animation', 'comedy', 'family', 'crime', 'eu...         6.1
1277   ['animation', 'comedy', 'family', 'crime', 'eu...         6.1
1278   ['animation', 'comedy', 'family', 'crime', 'eu...         6.1
...                                                  ...         ...
26649                        ['comedy', 'documentation']         6.8
26650                        ['comedy', 'documentation']         6.8
26651                     ['comedy', 'romance', 'drama']         4.6
26652                     ['comedy', 'romance', 'drama']         4.6
37793                   ['comedy', 'fantasy', 'romance']         5.4

       imdb_votes
2207     115448.0
1274       1785.0
1276       1785.0
1277       1785.0
1278       1785.0
...           ...
26649      2616.0
26650      2616.0
26651      3157.0
26652      3157.0
37793     19482.0

[73859 rows x 9 columns]

Look through the list to find implicit duplicates of `'show'` (`'movie'` duplicates will be ignored since the assumption is about shows). These could be names written incorrectly or alternative names of the same genre.

You will see the following implicit duplicates:
* `'shows'`
* `'SHOW'`
* `'tv show'`
* `'tv shows'`
* `'tv series'`
* `'tv'`

To get rid of them, declare the function `replace_wrong_show()` with two parameters: 
* `wrong_shows_list=` — the list of duplicates
* `correct_show=` — the string with the correct value

The function should correct the names in the `'type'` column from the `df` table (i.e., replace each value from the `wrong_shows_list` list with the value in `correct_show`).

In [ ]:
# function for replacing implicit duplicates
wrong_shows_list = ['shows','tv show','tv shows','tv series', 'tv']
correct_show = 'SHOW'
def replace_wrong_show(wrong_shows_list, correct_show):
    df['type'] = df['type'].replace(wrong_shows_list, correct_show)

Call `replace_wrong_show()` and pass it arguments so that it clears implicit duplicates and replaces them with `SHOW`:

In [ ]:
# removing implicit duplicates
replace_wrong_show(wrong_shows_list, correct_show)

Make sure the duplicate names are removed. Print the list of unique values from the `'type'` column:

In [ ]:
# viewing unique genre names
unique_types = sorted(df['type'].unique())
print(unique_types)

['MOVIE', 'SHOW', 'movies', 'the movie']

### Conclusions <a id='data_preprocessing_conclusions'></a>
We detected three issues with the data:

- Incorrect header styles
- Missing values
- Duplicate rows and implicit duplicates

The headers have been cleaned up to make processing the table simpler.

All rows with missing values have been removed. 

The absence of duplicates will make the results more precise and easier to understand.

Now we can move on to our analysis of the prepared data.

## Stage 3. Data analysis <a id='hypotheses'></a>

Based on the previous project stages, you can now define how the assumption will be checked. Calculate the average amount of votes for each score (this data is available in the `imdb_score` and `imdb_votes` columns), and then check how these averages relate to each other. If the averages for shows with the highest scores are bigger than those for shows with lower scores, the assumption appears to be true.

Based on this, complete the following steps:

- Filter the dataframe to only include shows released in 1999 or later.
- Group scores into buckets by rounding the values of the appropriate column (a set of 1-10 integers will help us make the outcome of our calculations more evident without damaging the quality of our research).
- Identify outliers among scores based on their number of votes, and exclude scores with few votes.
- Calculate the average votes for each score and check whether the assumption matches the results.

To filter the dataframe and only include shows released in 1999 or later, you will take two steps. First, keep only titles published in 1999 or later in our dataframe. Then, filter the table to only contain shows (movies will be removed).

In [ ]:
# using conditional indexing modify df so it has only titles released after 1999 (with 1999 included)
# give the slice of dataframe new name
df_filtered = df[df['release_year'] >= 1999]
df_filtered

,name,character,role,title,type,release_year,genres,imdb_score,imdb_votes
1664,Jeff Probst,Himself - Host,ACTOR,Survivor,SHOW,2000,['reality'],7.4,24687.0
1955,Benicio del Toro,Franky Four Fingers,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
1956,Dennis Farina,Cousin Avi,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
1957,Vinnie Jones,Bullet Tooth Tony,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
1958,Brad Pitt,Mickey O'Neil,ACTOR,Snatch,MOVIE,2000,"['crime', 'comedy']",8.3,841435.0
...,...,...,...,...,...,...,...,...,...
85573,A??da Morales,Maritza,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85574,Adelaida Buscato,Mar??a Paz,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85575,Luz Stella Luengas,Karen Bayona,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85576,In??s Prieto,Fanny,ACTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0
85578,Julian Gaviria,unknown,DIRECTOR,Lokillo,the movie,2021,['comedy'],3.8,68.0

In [ ]:
# repeat conditional indexing so df has only shows (movies are removed as result)
df_filtered = df_filtered[df_filtered['type']== 'SHOW']
df_filtered

,name,character,role,title,type,release_year,genres,imdb_score,imdb_votes
1664,Jeff Probst,Himself - Host,ACTOR,Survivor,SHOW,2000,['reality'],7.4,24687.0
2076,Mayumi Tanaka,Monkey D. Luffy (voice),ACTOR,One Piece,SHOW,1999,"['animation', 'action', 'comedy', 'drama', 'fa...",8.8,117129.0
2077,Kazuya Nakai,Roronoa Zoro (voice),ACTOR,One Piece,SHOW,1999,"['animation', 'action', 'comedy', 'drama', 'fa...",8.8,117129.0
2078,Akemi Okamura,Nami (voice),ACTOR,One Piece,SHOW,1999,"['animation', 'action', 'comedy', 'drama', 'fa...",8.8,117129.0
2079,Kappei Yamaguchi,Usopp (voice),ACTOR,One Piece,SHOW,1999,"['animation', 'action', 'comedy', 'drama', 'fa...",8.8,117129.0
...,...,...,...,...,...,...,...,...,...
85433,Maneerat Kam-Uan,Ae,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.2,5.0
85434,Rudklao Amratisha,unknown,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.2,5.0
85435,Jaturong Mokjok,unknown,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.2,5.0
85436,Pisamai Wilaisak,unknown,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.2,5.0
85437,Sarawut Wichiensarn,unknown,DIRECTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.2,5.0

The scores that are to be grouped should be rounded. For instance, titles with scores like 7.8, 8.1, and 8.3 will all be placed in the same bucket with a score of 8.

In [ ]:
# rounding column with scores
df_filtered['imdb_score'] = df_filtered['imdb_score'].round(0)
#checking the outcome with tail()
df_filtered.tail()

/tmp/ipykernel_134/3907908562.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['imdb_score'] = df_filtered['imdb_score'].round(0)

,name,character,role,title,type,release_year,genres,imdb_score,imdb_votes
85433,Maneerat Kam-Uan,Ae,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.0,5.0
85434,Rudklao Amratisha,unknown,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.0,5.0
85435,Jaturong Mokjok,unknown,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.0,5.0
85436,Pisamai Wilaisak,unknown,ACTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.0,5.0
85437,Sarawut Wichiensarn,unknown,DIRECTOR,Let's Eat,SHOW,2021,"['drama', 'comedy']",8.0,5.0

It is now time to identify outliers based on the number of votes.

In [ ]:
# Use groupby() for scores and count all unique values in each group, print the result
df_filtered.groupby('imdb_score')['imdb_votes'].count()

imdb_score
2.0       24
3.0       27
4.0      180
5.0      592
6.0     2494
7.0     4706
8.0     4842
9.0      557
10.0       8
Name: imdb_votes, dtype: int64

Based on the aggregation performed, it is evident that scores 2 (24 voted shows), 3 (27 voted shows), and 10 (only 8 voted shows) are outliers. There isn't enough data for these scores for the average number of votes to be meaningful.

To obtain the mean numbers of votes for the selected scores (we identified a range of 4-9 as acceptable), use conditional filtering and grouping.

In [ ]:
# filter dataframe using two conditions (scores to be in the range 4-9)
df_filtered = df_filtered[(df_filtered['imdb_score']>= 4) & (df_filtered['imdb_score']<= 9)] 
df_filtered['imdb_score'] = df_filtered['imdb_score'].round()
# group scores and corresponding average number of votes, reset index and print the result
average_votes = df_filtered.groupby('imdb_score')['imdb_votes'].agg(['count', 'mean']).reset_index() 
average_votes

/tmp/ipykernel_134/1578808074.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filtered['imdb_score'] = df_filtered['imdb_score'].round()

   imdb_score  count           mean
0         4.0    180    5277.583333
1         5.0    592    3143.942568
2         6.0   2494    3481.717322
3         7.0   4706    8727.068211
4         8.0   4842   30299.460967
5         9.0    557  126904.109515

Now for the final step! Round the column with the averages, rename both columns, and print the dataframe in descending order.

In [ ]:
# round column with averages
average_votes['mean'] = average_votes['mean'].round()
# rename columns
average_votes.rename(columns={'imdb_score': 'score', 'mean': 'avg_votes'}, inplace=True)
# print dataframe in descending order
print(average_votes.sort_values(by='score', ascending=False))

   score  count  avg_votes
5    9.0    557   126904.0
4    8.0   4842    30299.0
3    7.0   4706     8727.0
2    6.0   2494     3482.0
1    5.0    592     3144.0
0    4.0    180     5278.0

The assumption macthes the analysis: the shows with the top 3 scores have the most amounts of votes.

## Conclusion <a id='hypotheses'></a>

The research done confirms that highly-rated shows released during the "Golden Age" of television also have the most votes. While shows with score 4 have more votes than ones with scores 5 and 6, the top three (scores 7-9) have the largest number. The data studied represents around 94% of the original set, so we can be confident in our findings.